AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CreateMessageLambda:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["arm64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: create_message/target/lambda/create_message/
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMO_DB_TABLE_NAME: !Ref MessageTable
      Events:
        GetMessageAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MessageApi
            Path: /messages
            Method: POST

  GetMessagesLambda:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: [ "arm64" ]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: get_messages/target/lambda/get_messages/
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMO_DB_TABLE_NAME: !Ref MessageTable
      Events:
        GetMessageAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MessageApi
            Path: /messages
            Method: GET

  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  MessageApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      OpenApiVersion: 3.0.3
